export const SCRAPING_URL = 'https://members.collegeofopticians.ca/Public-Register';

export enum UISelectors {
  LOADING_CONTENT_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_UpdateProgress1',
  LASTNAME_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input0_TextBox1',
  FIRSTNAME_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input1_TextBox1',
  INFORMALNAME_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input2_TextBox1',
  REGISTRATION_NUMBER_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input3_TextBox1',
  REGISTRATION_CLASS_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input4_DropDown1',
  REGISTRATION_STATUS_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input5_DropDown1',
  CONTACT_LENS_MENTOR_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input6_DropDown1',
  PRACTICE_NAME_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input9_TextBox1',
  CITY_OR_TOWN_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input10_TextBox1',
  POSTAL_CODE_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input11_TextBox1',
  AREA_OF_SERVICE_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_Input7_DropDown1',
  LANGUAGE_OF_SERVICE_SELECTOR = '.select2-hidden-accessible',
  FIND_BUTTON_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Sheet0_SubmitButton',
  TABLE_CONTENT_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Grid1_ctl00',
  CHANGE_PAGE_SIZE_BUTTON = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Grid1_ctl00_ctl03_ctl01_PageSizeComboBox_Input',
  PAGE_SIZE_50_CONTENT_SELECTOR = '#ctl01_TemplateBody_WebPartManager1_gwpciNewQueryMenuCommon_ciNewQueryMenuCommon_ResultsGrid_Grid1_ctl00_ctl03_ctl01_PageSizeComboBox_listbox li:nth-child(3)',
  PAGE_ITEM_CONTENT_SELECTOR = '.rgPagerCell .rgInfoPart',
  NEXT_BUTTON_SELECTOR = '.rgPageNext',
}
