service: cron-job-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  deploymentBucket:
    name: serverless-bucket-illumination

functions:
  triggerScrapeLambda:
    handler: main.js
    events:
      - schedule:
          rate: cron(0 0 * * ? *)  # Runs daily at midnight UTC
          enabled: true
