service: my-lambda-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  triggerScrapeLambda:
    handler: main.js
    events:
      - schedule:
          rate: cron(0 0 * * ? *)  # Runs daily at midnight UTC
          enabled: true
