name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: npx nx affected --target=lint
      # - run: npx nx affected --target=test
      - run: npx nx affected --target=build

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client
          # Start SSH agent
          eval "$(ssh-agent -s)"
          # Add SSH key
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          # Disable SSH host key checking
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          # Sync build files to EC2
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/assessment $USER@$HOST:$TARGET_DIR

      # Install Serverless Framework
      - name: Install Serverless
        run: npm install -g serverless

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Build cron-job-lambda project
      - name: Build the cron-job-lambda project
        run: npx nx affected --target=build cron-job-lambda

      - name: Prepare deployment directory
        run: |
          cp cron-job-lambda/serverless.yml dist/cron-job-lambda/
          cd dist/cron-job-lambda
          npm install --only=prod

      # Deploy Lambda function with Serverless
      - name: Deploy cron-job-lambda
        run: |
        cd dist/cron-job-lambda
        serverless deploy --config serverless.yml
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}  

